### PR TITLE
Fixed UX Issue

### LINKED ISSUE #18: UX Bug
## Solution 

Check if the link is valid then show the iframe

### PR DESCRIPTION
**Pull request by ParadoxPD**
#18

### CODE REVIEW

**Comment by bysimo** [comment]
@ParadoxPD can you explain in more detail about the bug you mean?
and give examples of inputs URL, current reality output, and expectation

you can also try to fix checking URL input if it's not youtube domain

**Comment by ParadoxPD** [comment]
### Right now, whenever there is a invalid input it shows a alert box but after that it still shows a embeddable iframe with an undefined link :
Screenshot 2021-10-07 221851
 
### The expected output should be, Not showing the iframe whenever there is a invalid input :
Screenshot 2021-10-07 222204

**Comment by ParadoxPD** [comment]
> @ParadoxPD can you explain in more detail about the bug you mean? and give examples of inputs URL, current reality output, and expectation
> 
> you can also try to fix checking URL input if it's not youtube domain

Ok I will fix the URL issue, and check if the link is a valid youtube link

**Comment by ParadoxPD** [comment]
@bysimo  Can you clarify one thing, why are you using regex for checking the URL instead of just using the ```startsWith()``` function?
### Example code:
Screenshot 2021-10-07 223437

**Comment by bysimo** [comment]
@ParadoxPD I also want users to be able to enter the URL of the mobile version of YouTube, for example: m.youtube.com
if we use _startsWith_ it will need a lot of code for the OR conditions

ok, i will merge your PR and fix other bugs. thank you for the contribution
happy coding :)

**Pull request merged**
