### PR TITLE
Added button to copy iframe code

### LINKED ISSUE #5: add button to copy iframe code
we need 1 person to add button to copy iframe HTML code into clipboard using javascript. so the user can press CTRL+V to paste the iframe code

### PR DESCRIPTION
**Pull request by KanishkKhurana**
a new button has been added to copy iframe code.
a new function called myFunction( ) has also been added to the javascript file.
i hope this helps.
please inform me if there are any problems 
happy hacking !

### CODE REVIEW

**Comment by bysimo** [comment]
@KanishkKhurana nice

**Comment by KanishkKhurana** [comment]
@bysimo please add "hacktoberfest-accepted " tag where you closed this PR. 
it'll really be helpful to me.
it says that my PR is not yet accepted at hacktoberfest

**Comment by bysimo** [comment]
@KanishkKhurana wait about a few minutes to see the update. it may take 10 minutes or more

**Comment by KanishkKhurana** [comment]
its here ! thank you so much !

**Comment by bysimo** [comment]
@KanishkKhurana you're welcome :)

**Pull request merged**
