### PR TITLE
Add Preview Of Generated HTML Code

### LINKED ISSUE #23: add a preview of the generated html code
show a preview of the embedded video using the code generated after the user clicks submit.

### PR DESCRIPTION
**Pull request by ishaanbedi**
Add Preview Of Generated HTML Code & Code Refactoring.
Check out the demo at: https://sopiler.ishn.xyz/

### CODE REVIEW

**Comment by bysimo** [comment]
@ishaanbedi please focus on the issue. code in other features that you have changed creates new bugs. refactoring and other stuff should be incorporated into the new issue.

**Comment by ishaanbedi** [comment]
> @ishaanbedi please focus on the issue. code in other features that you have changed creates new bugs. refactoring and other stuff should be incorporated into the new issue.

The way the function was designed before I modified it always generated the wrong id of the video! 
Anyways, reverting back to the default changes.

**Comment by bysimo** [comment]
@ishaanbedi can you copy the youtube link you are trying to embed here? so I can check it too. thank you

**Comment by ishaanbedi** [comment]
> @ishaanbedi can you copy the youtube link you are trying to embed here? so I can check it too. thank you

My bad! That issue was for one video, idk why:
Here's the link for the same: https://www.youtube.com/watch?v=rEa99-NQ9Bk&ab_channel=JamesQQuick

Rest, I'm restoring all the changes!

**Comment by bysimo** [comment]
@ishaanbedi ah I see, that's because the allowed characters in the regex code don't have a hyphen (-). I will create a new issue. Thank you

**Pull request merged**
